### ISSUE TITLE
Could help

### ISSUE THREAD

**Issue by Chris2011** [daycode/netbeans-ionic-plugin#1]
Hey,

great that you work on a Ionic project implementation and other stuff :). Maybe this can help you: http://plugins.netbeans.org/plugin/59028/ionicextension. It is a plugin, which implements the ionic components into the code completion. You can see the issues there, maybe you can fix those in your plugin too: https://github.com/hexaviewtech/ionic-netbeans-plugin/issues

Regards

Chris

P.S. Will you implement ionic2 too? I know it is alpha or preview but would be nice to have it as a first draft inside the plugin :)

**Comment by daycode** [comment]
Thank you, I already saw that project :) I didn't look at ionic2 yet, but I will when the stable version will be ready.

**Comment by Chris2011** [comment]
Ok thx, great. Thought it could be cool, if someone can add alpha features. But sure, make more sense for the full version.
